[meta title:"Education Interactive" description:"Short description of your project" /]
[var name:"triggerUpdate" value:false /]

[var name:"districtStateIndex" value:0 /]
[var name:"districtStates" value:` ['initial', 'extremes', 'income', 'taxes', 'recapture-1', 'recapture-2'] ` /]
[derived name:"districtState" value:` districtStates[districtStateIndex] ` /]

[nav /]
[div style:`{width: '100%', height:'100vh', position: 'fixed', top: 0, background: '#f3f1f2',
    backgroundSize: 'cover',
    backgroundPosition: '50% 30%', zIndex: -1} `/]

[Header
  title:"Hed TK: Education Interactive"
  subtitle:"Dek TK"
  author:"Matthew Conlen"
  authorLink:"https://twitter.com/mathisonian" /]

[div style:`{paddingTop: 120, paddingBottom: 120, background: 'white'}`]


As 2018 begins, the crisis of funding for Texas public schools is reaching a tipping point. Need among Texas school children is expanding at an unprecedented rate as school funding from the state is declining for traditional school districts. To make matters more complicated, the state legislature hasn't updated its funding formulas — called "weights" — designed to help districts with high concentrations of poverty since the 1980s. Together, this has raised alarm with legislators, policy analysts, and education leaders from across Texas who believe we are losing generations of Texans to a broken school finance system that the State Legislature hasn’t fixed for almost 50 years.
[br/]
[br/]

Despite being one of the most important expenditures among state and local governments, many have difficulty understanding what's wrong in Texas school finance because it has long been notoriously complex. If you stick with us by scrolling below, we’ll help explain in the simplest terms possible why so many in Texas are concerned for that the futures of 5.3 million school children are in jeopardy by a 50-year failure to fix school finance.


[/div]

[var name:"scrollValue" value:0 /]

[Feature value:scrollValue ]
  [Feature.Content]
    [FullScreen]
      [div][IntroChart value:` scrollValue ` className:"alt" /][/div]
    [/FullScreen]
  [/Feature.Content]

  [Waypoint ]
    The State of Texas has been growing tremendously. But the state is getting poorer faster than it’s getting bigger and adjustments—called "weights"—to help districts with high concentrations of poverty haven't been updated since the 1980s.
  [/Waypoint]
  [Waypoint ]
    The number of students who are economically disadvantaged has been increasing as well, from 1.7 million in 1995 to over 3 million in 2016.
  [/Waypoint]
  [Waypoint ]
    Increase in students who are economically disadvantaged has been outpacing the general population growth, rising from 46% in 1995 to 59% in 2016.
  [/Waypoint]
  [Waypoint ]
    The average amount of funding per student has increased during this period, individual districts are still feeling a squeeze.

    To understand why, we have to examine where school districts get their money.
  [/Waypoint]
  [Waypoint]
    Districts receive money from state, federal and local funds. Federal funding accounts for only about 9% of district revenue on average, with the majority coming from state and local sources. Local funding comes largely from property taxes.
  [/Waypoint]
  [Waypoint style:`{marginBottom: '50vh'}`]
    Since 2012 the proportion of funding coming from local property taxes has increased. While property poor districts have long had a hard time keeping up, wealthy districts now find themselves constrained by how unstable the system has become, with many struggling to balance budgets.
  [/Waypoint]
[/Feature]

[Section className:"short-bottom"  style:`{paddingTop: 60}`]

[div style:`{zIndex: 1}`]


[Slideshow currentSlide:districtStateIndex]
[Slide]
# A Virtual Gridlock

This reliance on local property taxes creates inequity in school funding: property wealthy districts are able to raise more money than poor districts with less effort. To address this, the state has instituted a program called **recapture** — commonly known as the "Robin Hood" plan — that redistributes funds from property wealthy districts to property poor districts.

While the program was designed to make school funding more fair, subsequent laws have created a holding pattern for both wealthy and poor districts.
[/Slide]
[Slide]
# A Virtual Gridlock

The state classifies school districts that above a certain threshold of property wealth per student as **property wealthy**.

The property wealth of districts varies greatly: Westhoff ISD has the highest property wealth per student, with over $24 million in property wealth per student; Boles ISD is on the other extreme with only about $32,000 per student in property wealth.

[/Slide]
[Slide]
# A Virtual Gridlock

Of the 1022 independent school districts in Texas, 379 (37%) are considered property wealthy by the state. These districts are all eligible to pay into the recapture fund, however because of exceptions only 230 of them actually contribute anything.

Of the districts that do pay, Austin ISD contributes the most, $265 million in 2016-17, accounting for about 18% of the total recapture revenue.
[/Slide]

[Slide]
# A Virtual Gridlock

The money is supposed to be redistributed to the school districts via state funding, however the state does not report how this money is being used or where it is going.

Folo found that property wealthy districts are hesitant to raise their property taxes (and increase their contribution to recapture) due in part to this lack of transparency by the state.


[/Slide]
[Slide]
# A Virtual Gridlock

While all independent districts receive funds from the state and federal government, the local property tax rate is the main mechanism for districts to raise additional funds.

There is a cap on how heavily property can be taxed: of the property poor districts, 43% percent are already taxing property at the highest allowable rate, compared with only 8% of property wealthy districts.

[/Slide]
[Slide]
# A Virtual Gridlock

This wealthy-wealthy divide is not restricted to property: property poor districts are more likely to have a higher proportion of economically disadvantaged students, many of them minorities. The graph at the right shows the relationship between property wealth per student and the proportion of economically disadvantaged students in a district.

What we are left with is a system that leaves both groups, property wealthy and property poor, left unwilling or unable to raise local property taxes — the one lever that they can pull to raise school funds.

[/Slide]
[/Slideshow]

[controls index:districtStateIndex length:`districtStates.length` /]

[/div]

[div className:"district-container"]
[div className:"district-viz"]
[DistrictComparison state:` districtState `   /]
[/div]
// [Slideshow currentSlide:` districtStateIndex `]
//   [Slide]
//   Of the TKTK independent school districts in Texas, TK% are property wealthy, and TK% are property poor.

//   [action onClick:` console.log(districtStateIndex); districtStateIndex = (districtStateIndex + 1) % districtStates.length `] Click to continue[/action]
//   [/Slide]
//   [Slide]
//   TKTK, the most property rich district has over $TKTK in wealth, while TKTK, the most property poor has only $TKTK.
//   [action onClick:` console.log(districtStateIndex); districtStateIndex = (districtStateIndex - 1) `]
//     Prev
//   [/action]
//   [action onClick:` console.log(districtStateIndex); districtStateIndex = (districtStateIndex + 1) % districtStates.length `] Click to continue[/action]
//   [/Slide]
//   [Slide]
//   While all districts receive funds from the state and federal government, if a district is in need of additional funding they must turn to local property taxes.

//   [action onClick:` districtStateIndex = (districtStateIndex + 1) % districtStates.length `] Click to continue[/action]
//   [/Slide]
//   [Slide]
//   Today,  % of property poor districts are funding at the maximum tax rate allowed by the state for ISDs while INSERT % property wealthy districts are funding well below the maximum allowed rate.

//   [action onClick:` districtStateIndex = (districtStateIndex + 1) % districtStates.length `] Click to continue[/action]
//   [/Slide]
//   [Slide]
//   In order to ease the burden on these districts, the state instituted the recapture program. However, due to a lack of transparency and incentive, TK% of eligible property rich districts don’t pay into the fund.
//   [/Slide]
// [/Slideshow]
[/div]
[/Section]

[Section className:"short column short-bottom" ]
[flex direction:"horizontal" fullBleed:true align:"around" className:"story-container" ]

[AudioHolder
  quote:"If we don't get this right, the future of Texas is bleak."
  person:"Kevin Brown"
  filename:"brown.m4a"
  image:"brown_PLACEHOLDER.jpg" /]
[AudioHolder
  quote:"Generations of children are being lost."
  person:"Dan Huberty"
  filename:"huberty.m4a"
  image:"huberty_PLACEHOLDER.jpg" /]

[AudioHolder
  quote:"Kids get one chance at an education."
  person:"Chandra Villanueva"
  filename:"villanueva.m4a"
  image:"villanueva_PLACEHOLDER.jpg" /]

[/flex]
[/Section]

[Section className:"short column" ]
[flex direction:"vertical" ]
# Combined, the future for the state’s 5.3 million children is at risk.

To find out how we got here, you have to go back to the west side of San Antonio in the early 70s when a group of Mexican-American families were locked in a Supreme Court battle against the state of Texas over whether Education is a constitutionally protected right. FIND OUT MORE.
[/flex]

[flex direction:"horizontal" fullBleed:true align:"around" className:"story-container" ]
[StoryTeaser /]
[StoryTeaser /]
[StoryTeaser /]
[/flex]

[/Section]


[analytics google:"UA-5866209-13" /]